### PR TITLE
Bokeh Clustering Plot

### PR DESCRIPTION
**Pull request by britthard**

### CODE REVIEW

**Comment by britthard** [comment]
@yamsgithub I expect to have this ready for review in a week, so end of day Thursday.

**Comment by britthard** [comment]
@yamsgithub i'm working on tagging selected pages. 

I've noticed some weird behavior. 

Say that you have two pages, one marked relevant and one marked irrelevant. If you tag them as relevant, the irrelevant page first has its tag removed, then has the positive tag applied. Also, it seems that multiple requests to the server are being sent to do this.

This is opposed to just taking a list of urls and a tag, and updating the tag field with the new tag. 

Is there an function I can easily call to handle all this logic for me?

**Comment by yamsgithub** [comment]
Yeah...currently the logic here is to first remove the existing mutually exclusive tags and then apply the current. And this is done with two requests. One to remove the tags and the other to apply tags. So it is actually 2 calls to the server.

It may be a bit involved to replace this behavior. I actually prefer it this way. As it does what is expected...which is first remove the tags that conflict with the currently applied tags.

The tags logic is specified in the crawlervis.js as follows:

 this.initTagsGallery(
    [
      'Relevant',
      'Irrelevant',
      'Neutral',
    ],
    {
      'Relevant': {
        applicable: true,
        removable: true,
        negate: ['Irrelevant'],
      },
      'Irrelevant': {
        applicable: true,
        removable: true,
        negate: ['Relevant'],
      },
      'Neutral': {
        isVirtual: true,
        applicable: true,
        removable: false,
        negate: ['Relevant', 'Irrelevant'],
      },
    });

This logic is used in the tagsgallery.js in the applyOrRemove method to first remove any conflicting tags and then apply the new tags.

**Comment by britthard** [comment]
Thanks @yamsgithub. I have another question. I noticed when applyOrRemove calls onTagActionClicked, the opt_items variable grabbed from the d3 graph has a "possible" attribute. Any idea where this attribute comes from? It doesn't appear to be sent through the initial data from `/getPages`.

**Comment by britthard** [comment]
@yamsgithub have you had a chance to look this over?

**Comment by yamsgithub** [comment]
I just tried. I get the following error when I try to run ddt.

(ddt)yamuna@watson:/media/data/yamuna/Memex/test/domain_discovery_tool$ ./bin/ddt-dev 
DDT_HOME  : /media/data/yamuna/Memex/test/domain_discovery_tool
NLTK_DATA : /media/data/yamuna/Memex/test/domain_discovery_tool/nltk_data
ACHE_HOME : /media/data/yamuna/miniconda2/envs/ddt/bin/../lib/ache/
PYTHONPATH: /media/data/yamuna/Memex/test/domain_discovery_tool:
ELASTICSEARCH_SERVER  http://localhost:9200/
ELASTICSEARCH_USER  
Traceback (most recent call last):
  File "/media/data/yamuna/Memex/test/domain_discovery_tool/vis/server.py", line 8, in <module>
    from bokeh_plots.clustering import selection_plot, empty_plot
  File "/media/data/yamuna/Memex/test/domain_discovery_tool/vis/bokeh_plots/clustering.py", line 4, in <module>
    from bokeh.io import vform
ImportError: No module named bokeh.io

**Comment by britthard** [comment]
Maybe you are using the wrong bokeh version. Can you do `conda env update`?

**Comment by yamsgithub** [comment]
I did a conda env update. But the problem still persists.

**Comment by britthard** [comment]
ok. can you do `conda list bokeh`?

**Comment by yamsgithub** [comment]
It seems to be blank:

```
# packages in environment at /media/data/yamuna/miniconda2/envs/ddt:
#
```

**Comment by britthard** [comment]
Ok. I think I forgot to update the environment.yml file. I'll send a commit up in a couple seconds.

**Comment by britthard** [comment]
Should be ready for another go.

**Comment by yamsgithub** [comment]
Cool. It works now and looks good. There are these following issues:
1. The terms are no longer appearing
2. I think it may still be better to leave the lasso selection circle visible. I know you are making the selected dots solid. But it is not very discernible. Especially when there are overlapping dots.
3. When I do an update after tagging pages relevant or irrelevant I no longer see the tagged pages. The whole cluster changes even when I am looking at the same pages or at least it should be the same pages.
4. Once I select a set of pages and tag them then re-selecting the same pages again does not seem to work.

I will update more issues as I see them.

**Comment by yamsgithub** [comment]
Please ignore issues 1 and 3. I was using an index whose data was getting updated.

1 and 4 are related. Since it is not obvious that those pages are still selected.

**Comment by britthard** [comment]
So it looks like when the button is pressed, it makes the pagesGallery empty. I will look into any changes I have made to see where this bug might be happening.

**Comment by britthard** [comment]
@yamsgithub there are some small fixes that have to be done here with regard to the pagesGallery. Getting pulled away by Katrina to work on other stuff right now. I'll finish this up early monday.

**Comment by yamsgithub** [comment]
Sure. Sounds good.

**Comment by britthard** [comment]
@yamsgithub this is ready for another look. The pagesgallery is a bit finnicky, but everything seems to be working fine.

**Comment by yamsgithub** [comment]
Great! Will give it a try. Thanks!

**Comment by britthard** [comment]
@yamsgithub can we get this merged today?

**Comment by yamsgithub** [comment]
Yes. We can do that. I have made quite  a few changes to add some additional page filtering. I am checking in the code right now. We can merge your code after that.

**Comment by britthard** [comment]
@yamsgithub how's it working?

**Comment by yamsgithub** [comment]
There are two issues:
1. I think it may still be better to leave the lasso selection circle visible. I know you are making the selected dots solid. But it is not very discernible. Especially when there are overlapping dots.
2. After tagging the selected dots when you do an update the tags initially go back to the previous state and only get updated to the selected tags after the update is done. This make it look like you momentarily lost the tagging.

**Comment by britthard** [comment]
In regards to (1), as far as I can tell, there is not currently a way to make the bokeh lasso stay visible after selection. I can make modifications to the dots themselves to make them more visible in some way, but that's all I can do right now.

In regards to (2), I am refreshing the plot after you change the tags in the pages gallery, so any selection info is refreshed. There's not really a way around this without integrating Bokeh server. The choice here is either to show no change on the plot when you change a tag in the tags gallery (which would be confusing to the user), or show a new plot without any selections.

**Comment by britthard** [comment]
@yamsgithub would it be better to talk via hangout about this?

**Pull request merged**
