### PR TITLE
Statistics Dashboard

### PR DESCRIPTION
**Pull request by britthard**

### CODE REVIEW

**Comment by britthard** [comment]
@yamsgithub this is ready for review.

**Comment by yamsgithub** [comment]
Comments on the dashboard:
1. The dashboard was supposed to be accessed from a tab on the menu bar.
2. The domain table has only 10 entries while there definitely should be more. Are you displaying only the top 10?
3. The data fetched by time should be plotted by domain
4. Currently we are not able to custom select the domains to plot
5. It does not seem to be able to handle larger datasets of 1000's of documents. There seems to be a request time out on the elasticsearch search query. This can be fixed by passing a request_timeout=300 (in seconds for example) to the es.search query.

**Comment by britthard** [comment]
Thanks @yamsgithub , i'll give my comments on each of these.

1) This is a simple fix, and I can push up a commit immediately that will address this concern.
2) How many items do you want to show per table? How many items do you want to show on the plot?
3 & 4) I think that these things are out of scope for this part of the project. We will have to discuss this at the meeting today.
5) Are you getting specific bugs with timeouts? Is the page failing to load? Is it simply taking too long to load? Some clarification is needed here.

**Comment by yamsgithub** [comment]
1) 2. All the domains should be listed in the table.The plot can show the top 10
2) 3. & 4.  What part of the project are we talking about? Cross filtering data for the plot is a mandatory requirement for the dashboard.
3) 5. I am getting the following error when the data is quite large.

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/media/data/yamuna/miniconda2/envs/ddt/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/media/data/yamuna/miniconda2/envs/ddt/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/media/data/yamuna/miniconda2/envs/ddt/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/media/data/yamuna/Memex/test/domain_discovery_tool/vis/server.py", line 287, in statistics
    pages_dates = self._crawler.getPagesDates(session)
  File "/media/data/yamuna/Memex/test/domain_discovery_tool/vis/crawler_model_adapter.py", line 180, in getPagesDates
    return self._crawlerModel.getPagesDates(session)
  File "/media/data/yamuna/Memex/test/domain_discovery_tool/models/crawlermodel.py", line 933, in getPagesDates
    return get_pages_datetimes(es_info["activeCrawlerIndex"])
  File "/media/data/yamuna/Memex/test/domain_discovery_tool/elastic/get_documents.py", line 200, in get_pages_datetimes
    items = es.search(index_name, size=100000)["hits"]["hits"]
  File "/media/data/yamuna/miniconda2/envs/ddt/lib/python2.7/site-packages/elasticsearch-1.6.0-py2.7.egg/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(_args, params=params, *_kwargs)
  File "/media/data/yamuna/miniconda2/envs/ddt/lib/python2.7/site-packages/elasticsearch-1.6.0-py2.7.egg/elasticsearch/client/__init__.py", line 506, in search
    params=params, body=body)
  File "/media/data/yamuna/miniconda2/envs/ddt/lib/python2.7/site-packages/elasticsearch-1.6.0-py2.7.egg/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/media/data/yamuna/miniconda2/envs/ddt/lib/python2.7/site-packages/elasticsearch-1.6.0-py2.7.egg/elasticsearch/connection/http_urllib3.py", line 82, in perform_request
    raise ConnectionTimeout('TIMEOUT', str(e), e)
ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=10))

**Comment by britthard** [comment]
@yamsgithub this is ready for another look.

**Comment by yamsgithub** [comment]
The changes look fine. I will merge the PR

**Pull request merged**
