### PR TITLE
Add Domain Popup

### PR DESCRIPTION
**Pull request by britthard**
This is basically what the functionality will look like @yamsgithub .

### CODE REVIEW

**Comment by britthard** [comment]
Still polishing it.

**Comment by yamsgithub** [comment]
@brittainhard I updated to your most recent changes and it is looking good.

**Comment by britthard** [comment]
Great. I'm going to try to write some code to move the add domain button down to the bottom of the dropdown, and after that it should be ready to be reviewed.

**Comment by britthard** [comment]
@yamsgithub this is ready for review.

**Comment by yamsgithub** [comment]
1. All text forms should be behind the grey window when add domain is selected
2. Move the body of the rest of the ddt interface up closer to the menu
3. Change to mouse pointer when hovering over the domain name

**Comment by yamsgithub** [comment]
1. The menu is not aligned with the GUI at the bottom
2. Add NYU logo before the name of the tool on the menu

**Comment by britthard** [comment]
@yamsgithub where can I get a decent copy of the logo?

**Comment by yamsgithub** [comment]
http://engineering.nyu.edu/services/communications/identity has some logos. We think the black and white ones should be better.

**Comment by britthard** [comment]
So those logos are kind of large. It's going to take up a lot of real estate on the navbar. I don't have photoshop or illustrator on this computer so making any design changes to the logo itself is not really possible.

**Comment by britthard** [comment]
@yamsgithub is that the logo you want?

**Comment by yamsgithub** [comment]
let me see

**Comment by yamsgithub** [comment]
https://www.nyu.edu/content/dam/nyu/advertisePublications/images/logos/CentralAdmin_Logoart.zip

https://www.nyu.edu/employees/resources-and-services/media-and-communications/styleguide/downloads.html

This zip file has a few logos you can use.Please pick the one that suits best.

**Comment by britthard** [comment]
@yamsgithub better?

**Comment by yamsgithub** [comment]
Yes it is better. I like the stacked version. Could you please make it a little smaller so there is some padding around the logo. It should be somewhat aligned to the image and Web Search below. So the name Domain Discovery Tool should be closer to the logo.

**Comment by britthard** [comment]
Changes made @yamsgithub

**Comment by yamsgithub** [comment]
Great! Looks good now.Thanks!

**Comment by britthard** [comment]
Awesome. So should I merge?

**Comment by yamsgithub** [comment]
Yes. Go ahead.

**Pull request merged**
