### PR TITLE
Download Model Button on Navbar

### PR DESCRIPTION
**Pull request by britthard**

### CODE REVIEW

**Comment by britthard** [comment]
@yamsgithub this is pretty straightforward. Let me know what you want me to do with it.

**Comment by yamsgithub** [comment]
@brittainhard Actually I was thinking more in terms of just another menu item. Not really a button there. So what you could have is a 'Model' menu dropdown. The drop down can have a 'Build' which when clicked performs the same function as the model button. Does that make sense? We are trying to create a menu bar on top like any other menu bar.

**Comment by britthard** [comment]
that more like it @yamsgithub ?

**Comment by yamsgithub** [comment]
Yes. Though it should be Model on the menu and Build on the button.

**Comment by britthard** [comment]
Just caught that :D

**Comment by britthard** [comment]
@yamsgithub let me know if you want me to merge this.

**Comment by yamsgithub** [comment]
Hi Brittain:

Yes you can merge it. Sorry I was a bit caught up with our SUG demo this
afternoon. It went well :-) We are looking forward to their feedback.

Thanks
Yamuna

**Comment by britthard** [comment]
Awesome.

**Pull request merged**
