### PR TITLE
Top Menu with Domain Selection

### LINKED ISSUE #30: seeds_generator/conf/queries.txt creates Merge Conflicts
Does this file need to be tracked by the repo? My PR at https://github.com/ViDA-NYU/domain_discovery_tool/pull/28 just got a merge conflict because of a merged change in this file.

### PR DESCRIPTION
**Pull request by britthard**
closes #30

### CODE REVIEW

**Comment by britthard** [comment]
Not quite ready yet. I encountered quite a few problems trying to change crawlervis.js. Hopefully this will be ready by the end of the day.

**Comment by yamsgithub** [comment]
Let me know if you need any help.

Thanks
Yamuna

**Comment by britthard** [comment]
@yamsgithub this is ready to be looked at. Let me know if there are any issues with crawler selection. With this code its hard to tell exactly what happens and when.

**Comment by yamsgithub** [comment]
@brittainhard Thanks! I tested the menu. I found the following issues:
1. When there are no domains available the select domains menu drop down shows weirdly
2. When a new domain is added the select domains drop down seems to be messed up
3. The status message panel is hidden behind the menu
4. The color scheme of the menu bar is different from the rest of the interface

**Comment by britthard** [comment]
@yamsgithub i'll fix the adding domains issue immediatley. The others will be fixed quickly too.

**Comment by britthard** [comment]
@yamsgithub I have been making progress, and I will have something much better for you very shortly.

**Comment by yamsgithub** [comment]
@brittainhard I checkedthe fixes you made. Thanks! There are a few more that I noticed now:
1. When a new domain is added it seems to be selected by default. We do not want to do this. The domain that was originally selected will remain until the user actually selects the new domain created. Currently the selection is not working after a new domain is added.

**Comment by britthard** [comment]
Currently working on that problem @yamsgithub .

**Comment by britthard** [comment]
@yamsgithub think I got that problem solved.

**Comment by yamsgithub** [comment]
@brittainhard I tested the changes. They all look good. Thanks. I think you can merge it now.

**Comment by yamsgithub** [comment]
@brittainhard Sorry...I just noticed that after adding a new domain the domain selection is not working anymore.

**Comment by britthard** [comment]
@yamsgithub is this when you add a new domain with no existing domains, or when you add a domain when there are already existing domains

**Comment by yamsgithub** [comment]
When I add when there are existing domains. Actually haven't tested the other case.

**Comment by britthard** [comment]
I think I know whats going on. I have to re-render the dropdown when a new domain is added because there is no surefire way to tell which crawler was the last one added, and when this is done the callback is reset. Will push a fix up soon.

**Comment by britthard** [comment]
worth a look @yamsgithub

**Comment by yamsgithub** [comment]
@brittainhard Its looking good now. I think you can merge now.

**Pull request merged**
