### PR TITLE
Add topic modeling via topik

### PR DESCRIPTION
**Pull request by gpfreitas**
This branch adds topic modeling capabilities to the Domain Discovery Tool (DDT) via Topik (1)[]

A few notes taken from commit 
- Make sure you have no ad blockers of any sort active in your browser. I had Privacy Badger installed and it was stopping the visualization from loading!
- To obtain session info for testing/debugging open the developer tools (I used Chrome dev tools this time) and go to the Network log. Load the main page,  http://localhost:8084, and filter to find info on the `getPagesSummary` call. Look in there in the Headers tab, Form Data -> session. There you will find the session info (mainly the domainID) that you can use for testing and debugging purposes.

### CODE REVIEW

**Comment by britthard** [comment]
@gpfreitas just noticed that topik has not been added to `environment.yml`.

**Comment by gpfreitas** [comment]
@brittainhard: Interesting. I'll add it. Something seems to be pulling it in as a dependency though. Anyway, I think we should be more explicit. Thanks!

Bokeh isn't in there either. Should I add it with `bokeh=0.10.0` ?

**Comment by gpfreitas** [comment]
Status: while the API allows you to choose tokenizer, vectorizer, model and visualizer, so far I only have tested:
- tokenizer: simple
- vectorizer: bag_of_words
- model: LDA
- visualizer: pyLDAvis, termite

Focus now will be on getting PLSA working.

**Comment by gpfreitas** [comment]
@brittainhard , @yamsgithub : should we merge this into master? There are a couple of features that I would like to add and bugs that I would like to fix (list below), but I feel that this shouldn't be a danger to users as the feature is not yet hooked in the UI. Furthermore, it may be useful to have it in master, so that the changes stay in sync with master. Having it in master would also allows us to start working on UI integration.

Here is the list of things that need to be fixed and/or added (please weigh in on the questions below):
- Bug: segmentation faults happen sometimes (commit b2940b0) when we call [Page.topicsvis](https://github.com/ViDA-NYU/domain_discovery_tool/blob/b2940b046c09dfa7fcbf372b7088b936c852b231/vis/server.py#L46). This could be a bug in [topik](https://github.com/ContinuumIO/topik). [**Edit:** It's not. See 718c87929edfacb3d373e02bc2ea3afc5d151016]
- Bug: in a previous version (commit e9c2b8c), we would sometimes obtain HTTP timeout errors when communicating with Elasticsearch (using when trying to store the model tokens in Elasticsearch). That was because we were wrapping the work in a `TopikProject` object in [Crawlermodel.topic_model](https://github.com/ViDA-NYU/domain_discovery_tool/blob/e9c2b8c5b92d4fac59e9504140a95be6f15c0162/models/crawlermodel.py#L978), which saves the model ad all the intermediate steps (tokens, vectors) of the model in Elasticsearch. We [stopped doing that since](https://github.com/ViDA-NYU/domain_discovery_tool/blob/b2940b046c09dfa7fcbf372b7088b936c852b231/models/crawlermodel.py#L978), which "solved the problem", but now we don't save the model in Elasticsearch anymore. In other words, the user would have to recompute the model every time. The model and visualization with about 100 pages runs in a handful of seconds, so I'm not sure if we should or should not save the model to Elasticsearch. If not, should we allow the user to export the model somehow? This could be a bug in [topik](https://github.com/ContinuumIO/topik). [**Edit:** for now, the approach of not saving the model to Elasticsearch seems to work, so we will ignore this bug]
- Bug: PLSA fails. Right now, only LDA modeling works. This _is_ a bug in [topik](https://github.com/ContinuumIO/topik).
- Feature (lower priority now): reiplement LDAvis in Bokeh. Currently it's implemented with [pyLDAvis](https://github.com/bmabey/pyLDAvis).

**Comment by yamsgithub** [comment]
@gpfreitas No...we should wait for a stable version and complete integration before we merge. That way it is easy to revert as a whole merge. You should in fact synch up your branch from master as often as you can. I don't see how merging with master makes UI integration easier.

**Comment by yamsgithub** [comment]
Additionally all known bugs need to be fixed before merging.

**Comment by gpfreitas** [comment]
Got it. Thanks for the quick reply.

**Comment by gpfreitas** [comment]
@yamsgithub ,

**Comment by gpfreitas** [comment]
Some notes from the debugging session this morning where we tried to figure out together the source of the segmentation faults:
- in `visualize`: vis_name is an explicit parameter, but it's not passed along
  in the call to `registered_visualizers[vis_name]`. 
- in `topik.visualizers.pyldavis._to_py_lda_vis` in one of the matrices it sets
  up, it may be trying to slice at a place where there is no data. Accessing
  data that it can't get to. (Katrina pointed out some point where
  matrices/dataframes get transposed). A cursory inspection of the
  dataframes/matrices in there in one particular run (with parameters that
  sometimes generate the segfault) did not reveal any problems though.
- When debugging, to stop the messages about requests on the terminal, close
  the DDT window. There may be better ways around this.
- pip install -e . to setup dev versions. Example where this is useful: we are
  developing DDT, but topik is a dependency and may contain bugs or need
  modifications. We can benefit from using a local devevelopment copy
  (versioned) of topik rather than the one used by conda install.
- It seems that CherryPy is serializing some objects that it shouldn't be.
  Evidence of this is that before a segfault, we had a call to
  `/Users/gpfreitas/local/opt/miniconda3/envs/ddt/lib/python2.7/site-packages/cherrypy/lib/encoding.py`.
  (look for a `__call__` method). This definitely deserves some investigation.
  Maybe when running the model and viz in the same method, some matrices were
  getting serialized because of the cherrypy.expose decorator.

Big thanks to the rest of the Memex team (@kriehl, @msarahan, @brittainhard , and @youngblood,
especially the first two) for all the help.

**Comment by gpfreitas** [comment]
Another problem that happens sometimes, and so far, only when calling pyLDAvis is that the application gets stuck when calling, for example:

`http://localhost:8084/topicsvis?domain=weapons&tokenizer=simple&vectorizer=bag_of_words&model=lda&visualizer=lda_vis&ntopics=5`

But if I change `lda_vis` to `termite`, it works. Even after it's "stuck" (so it's not unresponsive, it's just stuck, and passing different paraments gets it going).

By "stuck" I mean
- the contents of the browser window do not change
- a "in progress" circling icon appears on the tab of the application (Chrome/Mac)
- the terminal where `/bin/ddt-dev` was executed displays only `2016-01-18 17:07:52,688 : WARNING : too few updates, training might not converge; consider increasing the number of passes or iterations to improve accuracy` (different timestamp of course), which is the first thing logged after a request of `topicsvis`.

**Comment by gpfreitas** [comment]
Using the [faulthandler](https://pypi.python.org/pypi/faulthandler/) package (included in the standard library since python 3.3) I obtained the following traceback.

```
2016-01-19 07:58:56,830 : WARNING : too few updates, training might not converge; consider increasing the number of passes or iterations to improve accuracy
Fatal Python error: Fatal Python error: Segmentation fault

Thread 0x000000014d822000Segmentation fault (most recent call first):


  File "/Thread 0xU000000014d822000s (most recent call first):
e  File r"s//Ugspefrrse/igtpafsr/eliotcaal/opt/misn/ilcoocnadla/3o/petn/vmsi/ndidcto/nldiab3//peyntvhso/nd2d.t7//lsiibt/ep-yptahcokna2g.e7s//spiatned-apsa/cckoargee/si/nptaenrdnaasl/sc.oprye"/, line i2625n in t_errenbaulisl.dp_yb"l, line k2625n in o_sr_eabnudi_lbdl_kbllokcnso
s  File _"a/nUds_ebrlsk/lgopcfsr
e  File i"t/aUss/elrosc/aglp/ofprte/imtiansi/clooncdaal3//oepntv/sm/idnditc/olnidba/3p/yetnhvosn/2d.d7t//sliitbe/-ppyatchkoang2e.s7//psaintdea-sp/accokraeg/eisn/tpearnndaalss/.cpoyr"e, line /2531i in n_t_eirnniatl_s_.
p  File y", line 2535 in __init__
  File ./bin/ddt-dev: line 17: 24715 Segmentation fault: 11  python $DDT_HOME/vis/server.py
(ddt)0269-gpfreitas:domain_discovery_tool gpfreitas$
```

@msarahan pointed out that the grabled text looks like it came from two threads writing at the same time, so probably the segfault is due to a race condition. I'll look into this now.

**Comment by gpfreitas** [comment]
Ok, with the segfault problem solved, all we need now to close this PR is to:
- Make sure PLSA works. [**Edit:** fixed in d5deef1].
- Hook this functionality to the UI.

@brittainhard , you may want to start taking a look at how to integrate this to the UI now, as the API should not change (again, start at `Page.topicsvis` in `vis/server.py`).

Using Bokeh to do a LDAvis-type of visualization will be addressed in a different pull request.

**Comment by gpfreitas** [comment]
Commit a9cf131 should wrap up my work on this PR.

I suggest merging this into `master` and then doing the UI integration in a separate PR.

@yamsgithub, @brittainhard what do you guys think?

### Summary of the work so far

We have now topic modeling features available via calls to `localhost:8084/topicsvis` (plus some parameters). The general URL to call is 

```
http://localhost:8084/topicsvis?domain={domain}&tokenizer={tokenizer}&vectorizer={vectorizer}&model={model}&visualizer={visualizer}&ntopics={ntopics}
```

For example, the URL below will output a termite plot of a PLSA model with 12 topics of the corpus from my "weapons" domain (defined in DDT), where we used the simple tokenizer from topik and a bag-of-words vectorizer (also from topik):

```
http://localhost:8084/topicsvis?domain=weapons&tokenizer=simple&vectorizer=bag_of_words&model=plsa&visualizer=termite&ntopics=12
```

All the topic modeling functionality is coming from [topik](https://github.com/ContinuumIO/topik) so we are limited to the features available there. Currently those are:
- tokenizer: `simple`
- vectorizer: `bag_of_words`
- model: `lda`, `plsa`
- visualizer: `lda_vis` (provided by pyLDAvis currently), `termite` (via bokeh)

The modeling step is implemented in [CrawlerModel.make_topic_model](https://github.com/ViDA-NYU/domain_discovery_tool/blob/a9cf13121961c03b14e61194441fff4cc55a86d1/models/crawlermodel.py#L1067). The request handler is implemented in [Page.topicsvis](https://github.com/ViDA-NYU/domain_discovery_tool/blob/a9cf13121961c03b14e61194441fff4cc55a86d1/vis/server.py#L47). Note that this overwrites the [previous implementation of Page.topicsvis](https://github.com/ViDA-NYU/domain_discovery_tool/blob/master/vis/server.py#L42).

For more information, see the documentation of the methods listed above.

**Comment by gpfreitas** [comment]
Some improvements that could be done:

- Right now the topic models do not take into account any "relevant/irrelevant" tags the user may have placed in the main DDT application.
- Bokeh implementation of the lda_vis chart.

Any other ideas?

**Comment by britthard** [comment]
@yamsgithub have you tested this out yet?

**Comment by yamsgithub** [comment]
Not yet. Hopefully today

**Comment by yamsgithub** [comment]
@gpfreitas Could you please update to the master and make sure all is working well.

**Comment by britthard** [comment]
@yamsgithub just did a merge and tested it -- everything seems to be working fine.

**Comment by yamsgithub** [comment]
@gpfreitas Great...thanks. I will test it today.

**Comment by britthard** [comment]
@yamsgithub when is this going to get merged?

**Comment by yamsgithub** [comment]
Not till I have merged all the fixes I made to address the instabilities caused by the clustering graph changes. We are running some user testing now and fixing issues as we find them. So until this is stable I am not going to make any huge merges.

**Comment by britthard** [comment]
I currently have a PR up that addresses those bugs: https://github.com/ViDA-NYU/domain_discovery_tool/pull/64

**Comment by yamsgithub** [comment]
That PR adresses the bugs we found earlier. But the changes I made were to completely change the whole event flow of the bokeh clustering integration. So you would first have to merge all the fixes I made to that PR before we merge it.

**Comment by britthard** [comment]
When did you make these changes?

**Comment by yamsgithub** [comment]
Last Fri. I sent you the following email.

-------- Forwarded message ----------
From: Yamuna Krishnamurthy yamuna@nyu.edu
Date: Fri, Feb 5, 2016 at 6:01 AM
Subject: Lots of fundamental changes to the bokeh clustering graph data handling
To: Brittain Hard brittain.hard@continuum.io, Katrina Riehl kriehl@continuum.io

Hi Brittain:

The issues I was having of incorrect tag and pages gallery update were caused by multiple calls to the server to update the data each time a tag was updated. This caused the underlying data of the bokeh plot to change and subsequently incorrect updates to pages gallery.

Page data should be updated locally on the client side at all times other than when the update button is clicked. 

I have cleaned up the bokeh_controller.js considerably. Please take a look at in the branch yamuna/custom_tag. If there are any concerns please let me know else I will merge those changes in when I merge the branch.

Thanks
Yamuna

**Pull request merged**
