### PR TITLE
[WIP] Terms Menu Improvements

### PR DESCRIPTION
**Pull request by britthard**
Right now the shift-click feature is working, and resets to mouseover when the term is un shift-clicked.

Still trying to add an indicator which slows which term has been shift-clicked.

### CODE REVIEW

**Comment by britthard** [comment]
@yamsgithub the basic functionality for shift-click is working, but I am trying to put in an indicator for which item has been shift-clicked. The text items don't really have any selectors for me to attach to, so I have to figure out the right kind of query to grab them. 

This part should be ready tomorrow, and when you have some links for me to grab we can finish this PR up.

**Comment by britthard** [comment]
@yamsgithub take a look

**Comment by britthard** [comment]
just realized I need more logic. its selecting more than one item.

**Comment by britthard** [comment]
ready for review @yamsgithub

**Comment by yamsgithub** [comment]
I don't see the pin icons. Have you reverted to clicks? I tried shift+click
but that does not work. The only thing I still see is that click of context
opens the url. The mouse should indicate that the context is clickable. It
is not clear right now.

**Comment by britthard** [comment]
@yamsgithub this is what I currently see:

https://www.dropbox.com/s/r628f54pt2mnvkv/Screen%20Shot%202015-09-17%20at%202.59.03%20PM.png?dl=0

**Comment by britthard** [comment]
Just tried it on firefox. Icons arent showing. Wonderful.

**Comment by britthard** [comment]
@yamsgithub this should be fixed for firefox. there is currently a problem on safari of the pins not changing colors.

**Comment by britthard** [comment]
even worse, the colors on the pins show up when you open a new tab in safari. but only after.

**Comment by yamsgithub** [comment]
I am using chrome and don't see them.

**Comment by britthard** [comment]
@yamsgithub I honestly don't know what to tell you. Have you done a pull and a full refresh?

**Comment by britthard** [comment]
Maybe see if anyone else on your team can see the symbols.

**Comment by yamsgithub** [comment]
I am now able to see it. I had not received the latest pull which is
strange as the last few times the pull told me everything was up-to-date.

It looks great :-) The only issue is that the pin is overlapping the delete
icon when a custom term is added.

**Comment by britthard** [comment]
Oh. Didn't know about that. Can we just move the delete icon to after the word?

**Comment by yamsgithub** [comment]
You can try. But I have a feeling it will not look good. Can we not just
have them beside each other?

Another issue I found was that if you have pinned a term and then click on
another term to mark it relevant then the pinned state persists. The pin
for the originally pinned term turns grey so you no longer know which term
you need to un-pin.

**Comment by britthard** [comment]
Ok. I will get these issues done early tomorrow.

**Comment by britthard** [comment]
The spacing issue has been solved. Trying to figure out what is causing the pins to lose their color.

**Comment by yamsgithub** [comment]
Great! I think it is just a matter of handling the events in the right order and disabling some events.

**Comment by britthard** [comment]
@yamsgithub I was generating the d3 objects incorrectly. I was failing to wrap the pin image in a `<g>` tag. That latest commit should fix the color loss issue.

**Comment by britthard** [comment]
I'm going to take a stab at why these icons are breaking in Safari.

**Comment by britthard** [comment]
@yamsgithub there seems to be very strange bugs happening with safari. I think we should consider moving these to a separate issue, which I can work on next week. What do you think?

**Comment by yamsgithub** [comment]
Sounds good to me.

**Comment by britthard** [comment]
Ok, i'll go ahead and merge this then. Thumbs up?

**Comment by yamsgithub** [comment]
Let me check it quickly.

**Comment by yamsgithub** [comment]
Hmmm...I again don't see any of your changes!

**Comment by yamsgithub** [comment]
I did repeated git pulls.

**Comment by yamsgithub** [comment]
Never mind. I just needed to do a bunch of refreshes. Sorry for the
confusion.

**Comment by britthard** [comment]
So.. merge? :)

**Comment by yamsgithub** [comment]
Almost there. Everything is looking good. I am just trying to see if I can
swap the delete and pin images.

**Comment by britthard** [comment]
Oh. That's just a matter of changing their x / y coordinates. I guess in this case, swapping them.

**Comment by yamsgithub** [comment]
Cool...Just did that :-) Thanks! I will check that in

**Comment by yamsgithub** [comment]
I updated a couple of changes. You can merge after you check them.

**Comment by britthard** [comment]
Looks good to me. Merging.

**Pull request merged**
