### PR TITLE
Revert "Bokeh Clustering Plot"

### PR DESCRIPTION
**Pull request by yamsgithub**
Reverts ViDA-NYU/domain_discovery_tool#51

Reverting as the changes are affecting query based filtering.

### CODE REVIEW

**Comment by yamsgithub** [comment]
@brittainhard I had to revert the pull request as I noticed that the "Select Queries" is not working with your changed. Could you please check this?

**Comment by britthard** [comment]
@yamsgithub what exactly is "Select Queries" ?

**Comment by yamsgithub** [comment]
Its when you select "Queries" in the page filtering which shows a "Select Queries" button. When you click on the button it should show a modal with the current queries for that domain. The modal does not show up properly

**Comment by britthard** [comment]
I'm still not seeing this on the page. Where on the page is this located?

**Comment by britthard** [comment]
@yamsgithub I think I see it now. This was added while I was working on my PR, if I recall. I'll try to get it working

**Comment by britthard** [comment]
This should be a simple fix. Somewhere, vis.queries is being set to undefined. I just have to find out where. Also there is a small UI issue to fix.

**Comment by britthard** [comment]
@yamsgithub can we close this since we fixed the problems with the clustering plot?

**Comment by yamsgithub** [comment]
I think we can do this. Just one more problem that is more immediate to fix. 

The URLs tooltip is very annoying as it appears as you move the mouse over the circles. Can you please  change this to appear only when the mouse is no longer moving? 

You can check the behaviour on the D3 version.

**Comment by yamsgithub** [comment]
I am guessing this should be a quick fix?

**Comment by britthard** [comment]
@yamsgithub i am currently working on the statistics dashboard PR, but I will be more than willing to fix these issues after we merge the dashboard code. I think it might be a good idea to rewrite https://github.com/ViDA-NYU/domain_discovery_tool/issues/52 to reflect the problems with the current graph? Would you mind putting all of these issues there?

**Comment by yamsgithub** [comment]
OK...we can close this and I can open one with all the issues that need to be fixed.

**Pull request closed without merging**
