### PR TITLE
Minimize white-space around center plot

### PR DESCRIPTION
**Pull request by canavandl**
Ready for merge

looks like:

screen shot 2016-03-30 at 12 31 25 pm

### CODE REVIEW

**Comment by canavandl** [comment]
ping @yamsgithub for review

We can also mess w/ the horizontal spacing too, if necessary.

**Comment by aecio** [comment]
Looks like this PR is also related to issue #62. Does it fix that problem too?

**Comment by britthard** [comment]
@aecio I think we did a workaround fix to that issue by allowing you to zoom in / out of the plot.

**Comment by britthard** [comment]
@yamsgithub this is ready to be merged as well.

**Comment by yamsgithub** [comment]
@brittainhard @canavandl I just tested this. Looks like the spacing between tag buttons and the visualization window is fixed. But the space between the forwardlinks,backlinks button and the tag button row is still quite large. 
ddt

**Comment by yamsgithub** [comment]
@brittainhard @canavandl Also could you make the height of the cluster window smaller, say like 300px?

**Comment by yamsgithub** [comment]
@canavandl Could you please change the order of the widgets with the custom inputs following the tag buttons.

**Comment by canavandl** [comment]
@yamsgithub 

I swapped the tags/custom inputs ordering and reduced the plot height to 300px. Here's a screenshot for me:

screen shot 2016-04-11 at 7 36 59 pm

I wasn't able to reproduce the large spacing between the tags buttons and forwardlinks/backlinks button rows on either current Chrome/FF/Safari for OS X. Can you update checkout of this branch and see if it's still there, and let me know what browser/platform you're using?

**Pull request merged**
