### PR TITLE
Fixed Dockerfile to used conda-based build and removed fabfile and pip support

### PR DESCRIPTION
**Pull request by aecio**
- Fixes Dockerfile to used conda-based build
- Removes fabfile and pip support
- Exposes supervisord port in the docker container

I think this is ready to be tested and merged.
@yamsgithub

### CODE REVIEW

**Comment by ahmadia** [comment]
@yamsgithub @aecio - should we merge this?

**Comment by aecio** [comment]
I think so, this is working for me. Did anyone test it? @yamsgithub?

**Comment by ahmadia** [comment]
My only comment is this binds the server to 0.0.0.0 by default, which means your laptop is listening to anybody else on the network who wants to connect it.  It's better security-wise to have the Docker install sed/patch this file or to use a different supervisor configuration.  Here's an example in-place sed-patch.

```
sed -i "s#command=python manage.py runserver 127.0.0.1:8000#command=python manage.py runserver 0.0.0.0:8000#g" supervisord.conf
```

**Comment by aecio** [comment]
You're right. I just fixed it. Thanks!

**Pull request merged**
