### PR TITLE
Plot and Code Fixes (#64 fixed)

### PR DESCRIPTION
**Pull request by remram44**
This is #64 but works around the brokenness of #58.

### CODE REVIEW

**Comment by britthard** [comment]
@remram44 would you like for me to fix the merge conflicts here?

**Comment by yamsgithub** [comment]
@brittainhard Yes...please fix the merge conflicts.

**Comment by yamsgithub** [comment]
There are 2 issues:
1. For the clustering plot the zoom does not let you control which part of the cluster you can zoom. 
2. Why is there a separate tab for plotting the endings? Why is it not just a plot aligned with the table. It is rather confusing to see the table and not see the plot till you go to the endings tab

**Comment by britthard** [comment]
@yamsgithub 
1. You can control where to zoom on based on where your mouse pointer is located. If need be I can also add a box zoom capability.
2. I made it that way because in the mockups you sent me, you has the URL endings and URL domains in the same area. I just thought that it would be best to represent those as tabs on a plot. If you would like   me to move the endings plot below the other two plots, I can do that. Just let me know.

**Comment by yamsgithub** [comment]
1. OK I checked the zoom again with your suggestion and it seems to be fine. So no changes required here.
2. Yes. Please move the URL endings below the URL domains

**Comment by britthard** [comment]
@yamsgithub please take another look.

**Comment by britthard** [comment]
@yamsgithub this is ready to merge

**Pull request merged**
