### PR TITLE
Fixed spacing.

### PR DESCRIPTION
**Pull request by britthard**

### CODE REVIEW

**Comment by britthard** [comment]
@yamsgithub this should fix it

**Comment by yamsgithub** [comment]
@brittainhard It did not fix the issue. All plots are still merged.

**Comment by britthard** [comment]
Hmm. Maybe you need to do a hard refresh `ctrl-shift-r`? That tells me that the stylesheet is still cached.

**Comment by yamsgithub** [comment]
@brittainhard Awesome...that worked :-) Thanks!

**Pull request merged**
