### PR TITLE
[WIP] Various UI Bugs

### LINKED ISSUE #40: Set the cursor at the beginning of the text box in the add new domain window
Allow the user to start adding the domain name without having to click on the textbox.

### PR DESCRIPTION
**Pull request by britthard**
Closes #40

### CODE REVIEW

**Comment by britthard** [comment]
@yamsgithub we're having our hackathon with JPL for the next two days, so I will have to put this PR on hold until wednesday.

**Comment by yamsgithub** [comment]
@brittainhard Sure.

**Comment by britthard** [comment]
@yamsgithub were you able to recreate this part of https://github.com/ViDA-NYU/domain_discovery_tool/issues/39 ? "Sometimes the term added as relevant (blue) shows up as irrelevant (red) on the terms list"

**Comment by yamsgithub** [comment]
@brittainhard I no longer see that issue. Maybe it was a side effect of the bug you fixed?

**Comment by britthard** [comment]
Not sure. Could have been. Can I go ahead and merge this?

**Comment by yamsgithub** [comment]
@brittainhard Yes. I think you can merge this. We can address the issue if it arises again.

**Pull request merged**
